# Rescan feed channels time, in seconds
update = 900

# Database connection setup
# * see crates/mysql/database
[mysql]
host = "localhost"
port = 3306
user = ""
password = ""
database = "rssto"

# Content sources (unlimited)
[[channel]]
url = "https://"
items_limit = 20
persist_item_title = true
persist_item_description = true
# optional:
# content_title_selector = "h1"
# content_description_selector = "article"

[[channel]]
url = "https://"
items_limit = 20
persist_item_title = true
persist_item_description = true
# optional:
# content_title_selector = "h1"
# content_description_selector = "article"